[versions]
agp = "8.5.2"
kotlin = "2.0.21"

koin = "4.1.1"
apollo = "3.7.0"
okhttp = "4.12.0"
datastore = "1.2.0"

appcompat = "1.7.1"
material = "1.13.0"
constraint = "2.2.1"

navigation = "2.8.4"
lifecycle = "2.10.0"
fragment = "1.8.9"
firebase-bom = "33.5.1"
browser = "1.5.0"
coil = "2.7.0"

camerax = "1.4.1"
mlkit_barcode = "17.3.0"
googleServices = "4.4.2"



[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint" }
apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }

navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
camerax-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camerax-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camerax-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }

mlkit-barcode = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit_barcode" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-database = { module = "com.google.firebase:firebase-database-ktx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
